### ISSUE TITLE
Wrong placeholder for Email field in Registration

### ISSUE THREAD

**Issue by kapxapot** [ricardo-campos-org/react-typescript-todolist#134]
## Describe the Bug
The Email field placeholder says "Type your password" during the registration.
https://tasknoteapp.dev.br/register

## Expected Behaviour
It should say "Type your email" instead.

**Comment by RMCampos** [comment]
Good catch! Like they say, one new feature added, one or more bugs coming along =D

I'll fix ASAP. ;)
