### ISSUE TITLE
Change language after authentication

### ISSUE THREAD

**Issue by kapxapot** [ricardo-campos-org/react-typescript-todolist#135]
## Brief description

The language selection is available only on the main page before registering/logging in.

## User Story

As a user, I want to be able to switch the language after authentication too.

## Acceptance Criteria

- [ ] One..
- [ ] Two..
- [ ] Tests passing
- [ ] PR merged

## Additional context

- Add any other context about the task here.
- Or here

**Comment by RMCampos** [comment]
@kapxapot 
There will be a user area covering this and other options as well.
For now I'll create a simple page just to give users this option. Hopefully next weekend this will be fixed

Thanks for the issue ;)
